import React, {useEffect, useRef, useState} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';

type Message={who:'YOU'|'ASSISTANT';text:string;sources?:any[];pending?:boolean};
type Snapshot={qualification_data?:{missing?:string[]};customer_profile?:Record<string,unknown>;business_details?:Record<string,unknown>;loan_requirement?:Record<string,unknown>;last_sources?:any[]};
type RealtimeEvent={timestamp_ms?:number;transcript?:{speaker:string;text:string;timestamp_ms:number};signals?:any[];nudges?:any[]};
const API_BASE_URL=(import.meta.env.VITE_API_BASE_URL||'http://localhost:8080').replace(/\/$/,'');
const api=async(path:string,body:unknown)=>{const r=await fetch(`${API_BASE_URL}${path}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw Error();return r.json()};
const suggestions=['How does the qualification process work?','What documents are needed?','What can the funding be used for?','Can I speak to a human?'];
const labels:Record<string,string>={full_name:'Full name',business_name:'Business name',business_type:'Business type',loan_purpose:'Funding purpose',requested_loan_amount:'Loan amount',years_in_business:'Years in business',contact_number:'Contact number'};
const profileLinks=[['GitHub','https://github.com/Dev-Moddh2211'],['LinkedIn','https://www.linkedin.com/in/dev-ashishkumar-moddh-28a505215']];
function Icon({name}:{name:string}){const p:Record<string,string>={spark:'M12 2l1.6 6.4L20 10l-6.4 1.6L12 18l-1.6-6.4L4 10l6.4-1.6L12 2z',plus:'M12 5v14M5 12h14',chat:'M5 5h14v10H8l-3 3V5z',book:'M4 5.5A2.5 2.5 0 016.5 3H19v15H6.5A2.5 2.5 0 014 15.5v-10z',pulse:'M3 12h4l2-6 4 12 2-6h6',mic:'M12 15a3 3 0 003-3V6a3 3 0 00-6 0v6a3 3 0 003 3zm-6-3a6 6 0 0012 0M12 18v3M8 21h8',send:'M4 4l16 8-16 8 3-8-3-8zm3 8h13',close:'M6 6l12 12M18 6L6 18',check:'M5 12l4 4L19 6',link:'M10 13a5 5 0 007.1.1l2-2a5 5 0 00-7.1-7.1l-1.1 1.1M14 11a5 5 0 00-7.1-.1l-2 2a5 5 0 007.1 7.1l1.1-1.1'};return <svg className="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d={p[name]||p.spark}/></svg>}
function Sidebar({view,setView,onNew,onProfile}:{view:string;setView:(v:string)=>void;onNew:()=>void;onProfile:()=>void}){return <aside className="sidebar"><div className="brand"><span className="brand-icon"><Icon name="spark"/></span>Resonate <b>AI</b></div><button className="new-button" onClick={onNew}><Icon name="plus"/>New conversation</button><nav>{[['conversation','chat','Conversation'],['knowledge','book','Knowledge Base'],['realtime','pulse','Realtime Insights']].map(([v,i,t])=><button className={view===v?'active':''} onClick={()=>setView(v)} key={v}><Icon name={i}/>{t}</button>)}</nav><div className="recent"><span className="eyebrow">Recent</span><span className="empty-recent">No saved conversations</span></div><div className="sidebar-bottom"><span className="eyebrow">Profile</span><button className="profile-link" onClick={onProfile}><span className="avatar">DA</span><span><strong>Dev AshishKumar Moddh</strong><small>View profile</small></span></button></div></aside>}
function TopBar({view,onMenu,onProfile,status}:{view:string;onMenu:()=>void;onProfile:()=>void;status:string}){return <header className="topbar"><button className="mobile-menu" onClick={onMenu} aria-label="Open navigation"><Icon name="chat"/></button><div><div className="workspace-title">{view==='realtime'?'Live Call Intelligence':view==='knowledge'?'Knowledge Base':'Business Loan Assistant'}</div><div className="workspace-subtitle">{view==='realtime'?'Realtime agent assist':'AI qualification workspace'}</div></div><div className="top-actions"><span className="connection"><i/>Connected</span><span className="status-pill">{status}</span><button className="top-profile" onClick={onProfile} aria-label="Open profile">DA</button></div></header>}
function Sources({sources}:{sources?:any[]}){if(!sources?.length)return null;return <div className="source-row"><span>Grounded in</span>{sources.slice(0,2).map((s,i)=><b key={i}>{s.source_id||s.source||'Verified source'}{s.version&&` · v${s.version}`}</b>)}</div>}
function MessageView({m}:{m:Message}){return <article className={`message ${m.who.toLowerCase()}`}><div className="speaker"><span className={m.who==='ASSISTANT'?'assistant-mark':'user-mark'}>{m.who==='ASSISTANT'?<Icon name="spark"/>:'You'}</span>{m.who==='ASSISTANT'?'Assistant':'You'}</div><div className="message-text">{m.text}</div><Sources sources={m.sources}/></article>}
function Welcome({onSuggestion,onStart}:{onSuggestion:(x:string)=>void;onStart:()=>void}){return <div className="welcome"><div className="welcome-mark"><Icon name="spark"/></div><span className="eyebrow">AI qualification workspace</span><h1>Business Loan Assistant</h1><p className="welcome-lead">Preliminary qualification only — not loan approval.</p><p className="welcome-copy">Collect business details, answer grounded questions, and handle qualification safely.</p><div className="suggestions">{suggestions.map(s=><button key={s} onClick={()=>onSuggestion(s)}>{s}</button>)}</div><button className="welcome-start" onClick={onStart}><Icon name="mic"/>Start a voice call</button></div>}
function Composer({value,setValue,onSubmit,onMic,disabled}:{value:string;setValue:(x:string)=>void;onSubmit:()=>void;onMic:()=>void;disabled:boolean}){const ref=useRef<HTMLTextAreaElement>(null);useEffect(()=>{if(ref.current){ref.current.style.height='auto';ref.current.style.height=`${Math.min(ref.current.scrollHeight,132)}px`}},[value]);return <div className="composer"><textarea ref={ref} value={value} disabled={disabled} placeholder="Ask about your loan, qualification, documents, or funding…" onChange={e=>setValue(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();onSubmit()}}}/><div className="composer-actions"><button className="icon-button" onClick={onMic} aria-label="Start voice call" disabled={disabled}><Icon name="mic"/></button><button className="send-button" onClick={onSubmit} aria-label="Send message" disabled={disabled||!value.trim()}><Icon name="send"/></button></div></div>}
function Context({snapshot}:{snapshot:Snapshot}){const fields=[...Object.entries(snapshot.customer_profile||{}),...Object.entries(snapshot.business_details||{}),...Object.entries(snapshot.loan_requirement||{})];const missing=snapshot.qualification_data?.missing||[];const total=fields.length+missing.length;return <aside className="context-panel"><div className="context-head"><div><span className="eyebrow">Context</span><h2>Qualification</h2></div><span>{fields.length} of {total||6}</span></div><div className="progress-track"><span style={{width:`${total?fields.length/total*100:0}%`}}/></div><p className="context-note">Only details shared in this conversation are shown.</p>{fields.concat(missing.map(x=>[x,'Not provided'] as [string,unknown])).map(([k,v])=><div className="field" key={k}><span className={v==='Not provided'?'pending':'collected'}>{v==='Not provided'?'○':<Icon name="check"/>}</span><div><small>{labels[k]||k.replaceAll('_',' ')}</small><strong>{String(v)}</strong></div></div>)}<div className="safety-note"><Icon name="check"/>Preliminary qualification only — not loan approval.</div></aside>}
function VoiceCard({status,mic,callId,onStart,onEnd}:{status:string;mic:string;callId:string|null;onStart:()=>void;onEnd:()=>void}){const active=!!callId;return <div className="voice-card"><div className="voice-card-head"><div><span className="eyebrow">Voice call</span><h2>{active?'Live conversation':'Ready when you are'}</h2></div><span className={`live-dot ${active?'on':''}`}>{active?'LIVE':'IDLE'}</span></div><div className={`voice-orb ${status.toLowerCase()}`}><span><Icon name="mic"/></span></div><div className="voice-state">{status==='LISTENING'?'Listening…':status==='THINKING'?'Processing…':status==='SPEAKING'?'Speaking…':status==='ERROR'?'Voice unavailable':active?'Call in progress':'Start a call to use voice'}</div>{mic==='Denied'&&<p className="inline-error">Microphone access was denied. You can continue using text.</p>}<button className="primary-button voice-button" onClick={active?onEnd:onStart}>{active?<><Icon name="close"/>End call</>:<><Icon name="mic"/>Start call</>}</button></div>}
function Realtime({events,onReplay,replayId}:{events:RealtimeEvent[];onReplay:()=>void;replayId:string|null}){const ts=events.filter(e=>e.transcript),nudges=events.flatMap(e=>e.nudges||[]),signals=events.flatMap(e=>e.signals||[]);return <div className="realtime-view"><div className="realtime-toolbar"><div><span className="eyebrow">Q4 · realtime agent assist</span><h1>Live Call Intelligence</h1><p>Incremental transcript, detected signals, and actionable nudges.</p></div><div className="realtime-actions"><span className={`live-dot ${replayId?'on':''}`}>{replayId?'LIVE':'IDLE'}</span><button className="primary-button" onClick={onReplay}><Icon name="pulse"/>Start WAV replay</button></div></div><div className="realtime-grid"><section className="insight-surface"><div className="surface-title"><h2>Live transcript</h2><span>{ts.length} events</span></div>{ts.length?ts.map((e,i)=><div className={`live-line ${i===ts.length-1?'latest':''}`} key={i}><time>00:{((e.transcript?.timestamp_ms||0)/1000).toFixed(1)}</time><div><b>{e.transcript?.speaker}</b><p>{e.transcript?.text}</p></div></div>):<div className="empty-panel"><Icon name="pulse"/><strong>Ready for a live replay</strong><span>Events will appear here as audio is processed.</span></div>}</section><section className="insight-surface"><div className="surface-title"><h2>Live nudges</h2><span>{nudges.length}</span></div>{nudges.length?nudges.map((n,i)=><div className={`nudge ${String(n.priority||'').toLowerCase()}`} key={i}><div className="nudge-top"><span>{n.priority}</span><time>00:{((n.timestamp_ms||0)/1000).toFixed(1)}</time></div><strong>{n.signal_id?.replaceAll('_',' ')}</strong><p>{n.text}</p>{typeof n.confidence==='number'&&<small>Confidence {n.confidence}</small>}</div>):<div className="empty-panel compact"><strong>No active nudges</strong><span>Recommendations appear when signals are detected.</span></div>}</section></div><section className="insight-surface signals"><div className="surface-title"><h2>Detected signals</h2><span>{signals.length}</span></div>{signals.length?signals.map((s,i)=><div className="signal-row" key={i}><i/>{s.signal_id?.replaceAll('_',' ')}<span>{s.priority||'—'}</span><time>00:{((s.timestamp_ms||0)/1000).toFixed(1)}</time></div>):<p className="quiet-empty">No signals detected yet.</p>}</section></div>}
function Profile({close}:{close:()=>void}){return <div className="overlay" onClick={close}><aside className="profile-panel" onClick={e=>e.stopPropagation()}><button className="close-button" onClick={close} aria-label="Close profile"><Icon name="close"/></button><div className="profile-avatar">DA</div><span className="eyebrow">Developer profile</span><h2>Dev AshishKumar Moddh</h2><p>B.Tech Information Technology<br/>Indian Institute of Information Technology, Sonepat</p><div className="profile-links">{profileLinks.map(([n,u])=><a href={u} target="_blank" rel="noopener noreferrer" key={n}>{n}<Icon name="link"/></a>)}</div></aside></div>}
function App(){const [view,setView]=useState('conversation'),[profile,setProfile]=useState(false),[menu,setMenu]=useState(false),[status,setStatus]=useState('READY'),[mic,setMic]=useState('Not started'),[callId,setCallId]=useState<string|null>(null),[messages,setMessages]=useState<Message[]>([]),[snapshot,setSnapshot]=useState<Snapshot>({}),[input,setInput]=useState(''),[events,setEvents]=useState<RealtimeEvent[]>([]),[replayId,setReplayId]=useState<string|null>(null),stream=useRef<MediaStream|null>(null),recognition=useRef<any>(null);
 const listen=()=>{if(!recognition.current||!callId)return;setStatus('LISTENING');try{recognition.current.start()}catch{}};const speak=(text:string,sources?:any[])=>{setMessages(m=>[...m,{who:'ASSISTANT',text,sources}]);setStatus('SPEAKING');if(!('speechSynthesis'in window)){listen();return}const u=new SpeechSynthesisUtterance(text);u.onend=listen;speechSynthesis.speak(u)};
 const submit=async(text=input)=>{if(!text.trim()||!callId)return;setInput('');setMessages(m=>[...m,{who:'YOU',text},{who:'ASSISTANT',text:'Retrieving verified information…',pending:true}]);setStatus('THINKING');try{const x=await api('/api/conversation/turn',{call_id:callId,message:text});setSnapshot(x.state||{});setMessages(m=>m.filter(v=>!v.pending));speak(x.response,x.sources||x.state?.last_sources)}catch{setMessages(m=>m.filter(v=>!v.pending));setMessages(m=>[...m,{who:'ASSISTANT',text:"I couldn't reach the assistant right now. Please check the connection and try again."}]);setStatus('ERROR')}};
 const start=async()=>{setStatus('MICROPHONE ACCESS');try{stream.current=await navigator.mediaDevices.getUserMedia({audio:true});setMic('Granted');const r=await api('/api/conversation/start',{});setCallId(r.call_id);setSnapshot(r.state||{});setMessages([{who:'ASSISTANT',text:r.response,sources:r.sources||[]}]);const R=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;if(R){const rec=new R();rec.lang='en-IN';rec.interimResults=false;rec.onresult=(e:any)=>submit(e.results[0][0].transcript);rec.onerror=()=>setStatus('ERROR');recognition.current=rec;setStatus('SPEAKING');if('speechSynthesis'in window){const u=new SpeechSynthesisUtterance(r.response);u.onend=listen;speechSynthesis.speak(u)}else listen()}else{setStatus('READY');setMessages(m=>[...m,{who:'ASSISTANT',text:"Voice recognition isn't available in this browser. You can continue using text input."}])}}catch{setMic('Denied');setStatus('ERROR')}};
 const end=async()=>{recognition.current?.stop();if('speechSynthesis'in window)speechSynthesis.cancel();stream.current?.getTracks().forEach(t=>t.stop());if(callId)await api('/api/conversation/end',{call_id:callId}).catch(()=>{});setCallId(null);setMic('Released');setStatus('ENDED')};
 const replay=async()=>{try{const r=await api('/api/realtime/start',{audio_path:'evidence/category5/audio/compliance.wav',replay_speed:1});setReplayId(r.call_id);setEvents([]);let cursor=0;const poll=async()=>{const x=await(await fetch(`${API_BASE_URL}/realtime/events?call_id=${r.call_id}&cursor=${cursor}`)).json();cursor=x.cursor;setEvents(old=>[...old,...x.events]);if(!x.completed)setTimeout(poll,250)};poll()}catch{setReplayId(null)}};
 const fresh=()=>{setMessages([]);setSnapshot({});setInput('');setCallId(null);setStatus('READY');setView('conversation');setMenu(false)};const suggestion=(s:string)=>{setInput(s);start()};
 return <div className="app-shell"><Sidebar view={view} setView={v=>{setView(v);setMenu(false)}} onNew={fresh} onProfile={()=>setProfile(true)}/>{menu&&<div className="drawer-backdrop" onClick={()=>setMenu(false)}/>}<div className="workspace"><TopBar view={view} onMenu={()=>setMenu(true)} onProfile={()=>setProfile(true)} status={status}/>{view==='realtime'?<Realtime events={events} onReplay={replay} replayId={replayId}/>:<div className="content-layout"><main className="main-content">{view==='knowledge'?<div className="knowledge-view"><span className="eyebrow">Q2 · source-grounded retrieval</span><h1>Knowledge Base</h1><p>The assistant uses the local synthetic source pack to answer grounded questions and preserves source metadata in responses.</p><div className="knowledge-note"><Icon name="book"/><div><strong>Available through Conversation</strong><span>Start a conversation to ask about qualification, documents, funding, or repayment.</span></div></div></div>:messages.length===0?<Welcome onSuggestion={suggestion} onStart={start}/>:<><div className="conversation-head"><div><span className="eyebrow">Conversation</span><h1>Business Loan Assistant</h1></div><span className="safety-badge">Preliminary only</span></div><div className="messages">{messages.map((m,i)=><MessageView m={m} key={i}/>)}</div></>}{view==='conversation'&&<div className="composer-wrap"><Composer value={input} setValue={setInput} onSubmit={()=>submit()} onMic={start} disabled={!callId||status==='THINKING'}/></div>}</main><div className="right-rail">{view==='conversation'&&<VoiceCard status={status} mic={mic} callId={callId} onStart={start} onEnd={end}/>}<Context snapshot={snapshot}/></div></div>}</div>{profile&&<Profile close={()=>setProfile(false)}/>}</div>}
createRoot(document.getElementById('root')!).render(<App/>);
